### ISSUE TITLE
Local version support and customization options

### ISSUE THREAD

**Issue by JStyle21** [edgelesssys/constellation#1838]
Hi,

My case is, i'm looking of a secure setup for k8s like constellation provides only i need it to wrap around my virtual cluster inside my actual cluster, i don't any cloud provider for this and i'm not sure the machine supports the needed encryption features you rely on from the processor. also from what i understand you only support a local cluster version for testing and only the cloud versions are production ready with only 3 providers supported, correct?

So my question is, would it be possible to have a local less secure version of what you offer using some configuration or does my use case requires a different product\solution? if it's the latter then maybe you can suggest something? if not then i thank you for you time anyway

**Comment by 3u13r** [comment]
Hey,

thanks for reaching out. I'm not sure what you mean by "wrap around my virtual cluster inside my actual cluster", but I wanted to highlight that Constellation is it's own standalone Kubernetes distribution. For instance, with a cloud subscription and our CLI you can start-up a Constellation without the need of a previously existing cluster.

You're totaly right in that our Miniconstellation offering (which is based on QEMU) is not intended for production use. Mainly because it lacks the security and functionality like scaling and upgrades. For a complete experience, we'd suggest deploying OpenStack first and then deploy Constellation on top of that. If you need help integrating Constellation with OpenStack, we can help you with that.

If you don't need a CC-secure Kubernetes and also don't need any public cloud functionality such as load balancers, storage (via our CSI drivers), or upgrades, but want to use Constellion then Constellation on QEMU (basically Miniconstellation) is the easiest way.

One test to check for the functionality is `cat /proc/cpuinfo | grep -i sev` and `cat /proc/cpuinfo | grep -i tdx` or to look up your current CPU.

If you could elaborate on your requirements and goals you want to achieve, maybe we could help you further.

**Comment by JStyle21** [comment]
Hey,
Thanks for the response, appreciate the info.

Let me try to explain my use case:

I think it would have a similarity to docker in docker, i'm trying to create a cluster inside of a cluster  that way i could manipulate it without having an impact on the original one whilst also still being connected to it so i could exchange info with it, when i said vcluster i meant this  [Project](https://github.com/loft-sh/vcluster) it allows you to create a new cluster insides a namespace of an existing cluster.

The problem with this setup would be security, it's messy just to operate now on top of that securing it is another mess, i thought maybe using a solution like constellation would save me some of the trouble since it has several elements already incorporated into it but now since it's clear that it's not really as modular as i thought i'm not sure it's possible would making heavy changes which would be the same as using other projects combined or doing something from scratch.

WDYT?

**Comment by 3u13r** [comment]
Depending on what "still being connected to it so i could exchange info with it" entails, you could have a look at ClusterAPI. This allows you to spin up separate K8s clusters which are being managed by a single root K8s cluster. Constellation does not currently support being created via ClusterAPI, but this is something we want to offer in the future. 

But you are right in that our security guarantees don't translate very well to your use-case especially if you don't have CC ready hardware.

**Comment by JStyle21** [comment]
> still being connected to it so i could exchange info with it
I mean creating a replica of a pod or a deployment in the vcluster from the host cluster so for that i need access to the k8s api to get the object data about the resource being replicated

ClusterAPI is nice but it's more of an automation for managing different scenario while i'm looking for something to replicate a production env inside of itself to play around with while also adding some security to prevent any tampering from the outside as much as possible, i don't think it is the right tool for the job but also Constellation isn't either

Thanks for the discussion and time tho and if there isn't anything else that comes to mind i will close this thread
