### ISSUE TITLE
Questions about the performance comparison

### ISSUE THREAD

**Issue by AmbitionXiang** [edgelesssys/constellation#3340]
Hi~ I noticed that Constellation performs even [faster than insecure AKS and GKS](https://constellation-docs.netlify.app/constellation/2.4/overview/performance) in terms of API latency. It is amazing! How did you do that? Why is it even faster than k8s without TEEs?

**Comment by burgerdev** [comment]
Hi @AmbitionXiang, 

I'm happy to see interest in Constellation's performance! The link you posted is for an older release (2.4), please also take a look at the improved benchmark tables in 2.17: https://constellation-docs.netlify.app/constellation/overview/performance/.

To answer your question: k8s API server request latency should usually not be CPU/memory-bound, so the effect of runtime encryption is often negligible. What we see in these graphs is likely a combination of:

* Increased network latency due to hosted k8s API server not being local to the cluster.
  - This should explain all the diff for read requests (GET, LIST).
* Additional work being done by the hosted API server (audit logging, tracing, synchronized replicated persistence).
  - May or may not be the reason for diff in CREATE/UPDATE/...

It's probably not a fair comparison after all, and we don't list it in the docs anymore - my takeaway from the numbers is that _Constellation latency is not worse than hosted alternatives_.

Cheers, Markus
